import { Recipe, GroceryItem } from '../types';

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: 'Spaghetti Carbonara',
    emoji: '🍝',
    time: '25 min',
    servings: 4,
    tags: ['Italian', 'Pasta', 'Quick'],
    ingredients: [
      '400g spaghetti',
      '200g pancetta or guanciale',
      '4 large eggs',
      '100g Pecorino Romano, grated',
      '100g Parmigiano-Reggiano, grated',
      '2 cloves garlic',
      'Freshly ground black pepper',
      'Salt for pasta water',
    ],
    steps: [
      'Bring a large pot of salted water to a boil and cook spaghetti until al dente.',
      'While pasta cooks, fry pancetta in a large skillet over medium heat until crispy. Set aside.',
      'In a bowl, whisk together eggs, Pecorino Romano, and Parmigiano-Reggiano. Season with black pepper.',
      'Reserve 1 cup of pasta cooking water, then drain pasta.',
      'Remove skillet from heat. Add hot pasta to the pancetta pan and toss well.',
      'Pour egg mixture over pasta, tossing quickly. Add pasta water a little at a time to create a creamy sauce.',
      'Serve immediately with extra cheese and black pepper.',
    ],
    savedAt: Date.now() - 86400000,
  },
  {
    id: 'r2',
    title: 'Avocado Toast',
    emoji: '🥑',
    time: '10 min',
    servings: 2,
    tags: ['Breakfast', 'Healthy', 'Vegetarian'],
    ingredients: [
      '2 ripe avocados',
      '4 slices sourdough bread',
      '2 eggs',
      '1 lemon, juiced',
      'Red pepper flakes',
      'Everything bagel seasoning',
      'Salt and pepper',
      'Microgreens for garnish',
    ],
    steps: [
      'Toast the sourdough bread until golden and crispy.',
      'Halve the avocados, remove pits, and scoop flesh into a bowl.',
      'Mash avocado with lemon juice, salt, and pepper to your desired consistency.',
      'Poach or fry eggs to your liking.',
      'Spread mashed avocado generously on toast.',
      'Top with an egg, red pepper flakes, everything bagel seasoning, and microgreens.',
      'Serve immediately.',
    ],
    savedAt: Date.now() - 172800000,
  },
  {
    id: 'r3',
    title: 'Chicken Tikka Masala',
    emoji: '🍛',
    time: '45 min',
    servings: 4,
    tags: ['Indian', 'Chicken', 'Spicy'],
    ingredients: [
      '700g chicken breast, cubed',
      '400ml coconut cream',
      '400g canned tomatoes',
      '1 large onion, diced',
      '4 cloves garlic, minced',
      '2 tbsp ginger, grated',
      '3 tbsp tikka masala paste',
      '1 tsp garam masala',
      '1 tsp turmeric',
      'Fresh cilantro',
      '2 tbsp vegetable oil',
      'Salt to taste',
    ],
    steps: [
      'Marinate chicken in tikka masala paste for at least 30 minutes.',
      'Grill or pan-fry marinated chicken until charred and cooked through. Set aside.',
      'Heat oil in a large pan, sauté onion until golden brown.',
      'Add garlic and ginger, cook for 2 minutes until fragrant.',
      'Add canned tomatoes, turmeric, and garam masala. Simmer for 10 minutes.',
      'Blend sauce until smooth, return to pan.',
      'Add coconut cream and cooked chicken, simmer for 15 minutes.',
      'Season with salt, garnish with cilantro. Serve with basmati rice or naan.',
    ],
    savedAt: Date.now() - 259200000,
  },
  {
    id: 'r4',
    title: 'Greek Salad',
    emoji: '🥗',
    time: '15 min',
    servings: 4,
    tags: ['Greek', 'Salad', 'Vegetarian', 'Healthy'],
    ingredients: [
      '4 large tomatoes, chopped',
      '1 large cucumber, sliced',
      '1 red onion, thinly sliced',
      '200g Kalamata olives',
      '200g feta cheese, cubed',
      '1 green bell pepper, sliced',
      '4 tbsp extra-virgin olive oil',
      '2 tbsp red wine vinegar',
      '1 tsp dried oregano',
      'Salt and pepper',
    ],
    steps: [
      'Combine tomatoes, cucumber, red onion, bell pepper, and olives in a large bowl.',
      'Whisk together olive oil, red wine vinegar, and oregano for the dressing.',
      'Pour dressing over vegetables and toss gently.',
      'Top with feta cheese cubes — do not crumble.',
      'Season with salt, pepper, and a pinch more oregano.',
      'Let sit for 5 minutes before serving.',
    ],
    savedAt: Date.now() - 345600000,
  },
  {
    id: 'r5',
    title: 'Banana Pancakes',
    emoji: '🥞',
    time: '20 min',
    servings: 3,
    tags: ['Breakfast', 'Sweet', 'Vegetarian'],
    ingredients: [
      '2 ripe bananas',
      '2 eggs',
      '1 cup all-purpose flour',
      '1 cup milk',
      '1 tbsp sugar',
      '1 tsp baking powder',
      '1/2 tsp vanilla extract',
      'Pinch of salt',
      'Butter for cooking',
      'Maple syrup to serve',
    ],
    steps: [
      'Mash bananas in a bowl until smooth.',
      'Add eggs, milk, and vanilla extract. Whisk to combine.',
      'Sift in flour, baking powder, sugar, and salt. Stir until just combined — do not overmix.',
      'Heat a non-stick pan over medium heat with a small pat of butter.',
      'Pour 1/4 cup batter per pancake. Cook until bubbles form, then flip.',
      'Cook 1-2 minutes on the other side until golden.',
      'Serve stacked with maple syrup and sliced banana.',
    ],
    savedAt: Date.now() - 432000000,
  },
  {
    id: 'r6',
    title: 'Beef Tacos',
    emoji: '🌮',
    time: '30 min',
    servings: 4,
    tags: ['Mexican', 'Beef', 'Quick'],
    ingredients: [
      '500g ground beef',
      '8 small corn tortillas',
      '1 packet taco seasoning',
      '1/2 cup water',
      '1 cup shredded cheddar cheese',
      '1 cup shredded lettuce',
      '2 tomatoes, diced',
      '1 avocado, sliced',
      '1/2 cup sour cream',
      'Fresh lime and cilantro',
    ],
    steps: [
      'Brown ground beef in a skillet over medium-high heat, breaking it up as it cooks.',
      'Drain excess fat from the pan.',
      'Add taco seasoning and water, stir to combine. Simmer for 5 minutes until sauce thickens.',
      'Warm tortillas in a dry skillet or directly over a gas flame.',
      'Assemble tacos: add beef, then cheese, lettuce, tomato, and avocado.',
      'Top with sour cream and a squeeze of lime.',
      'Garnish with fresh cilantro and serve immediately.',
    ],
    savedAt: Date.now() - 518400000,
  },
  {
    id: 'r7',
    title: 'Miso Ramen',
    emoji: '🍜',
    time: '40 min',
    servings: 2,
    tags: ['Japanese', 'Soup', 'Noodles'],
    ingredients: [
      '200g ramen noodles',
      '3 tbsp white miso paste',
      '4 cups chicken or vegetable broth',
      '2 soft-boiled eggs',
      '100g corn kernels',
      '2 spring onions, sliced',
      '100g bamboo shoots',
      '4 slices chashu pork or tofu',
      '1 tbsp sesame oil',
      '1 tsp soy sauce',
      'Nori sheets to garnish',
    ],
    steps: [
      'Soft-boil eggs for 6.5 minutes, then transfer to an ice bath. Peel and halve.',
      'Heat broth in a pot over medium heat. Whisk in miso paste until dissolved.',
      'Add soy sauce and sesame oil to the broth. Keep warm.',
      'Cook ramen noodles according to package instructions. Drain well.',
      'Divide noodles between bowls and ladle hot miso broth over them.',
      'Top with eggs, corn, bamboo shoots, chashu pork, and spring onions.',
      'Add a sheet of nori and drizzle with extra sesame oil.',
    ],
    savedAt: Date.now() - 604800000,
  },
  {
    id: 'r8',
    title: 'Chocolate Lava Cake',
    emoji: '🍫',
    time: '25 min',
    servings: 4,
    tags: ['Dessert', 'Chocolate', 'Baking'],
    ingredients: [
      '200g dark chocolate (70%)',
      '100g unsalted butter',
      '3 eggs',
      '3 egg yolks',
      '150g powdered sugar',
      '60g all-purpose flour',
      '1 tsp vanilla extract',
      'Pinch of salt',
      'Cocoa powder for dusting',
      'Vanilla ice cream to serve',
    ],
    steps: [
      'Preheat oven to 220°C (425°F). Grease 4 ramekins with butter and dust with cocoa powder.',
      'Melt chocolate and butter together in a double boiler or microwave. Stir until smooth.',
      'Whisk eggs, egg yolks, powdered sugar, and vanilla until pale and thick.',
      'Fold chocolate mixture into the egg mixture.',
      'Sift in flour and salt, fold until just combined.',
      'Divide batter among prepared ramekins. At this point they can be refrigerated for up to 24 hours.',
      'Bake for 10-12 minutes until edges are set but center is still jiggly.',
      'Run a knife around the edge, invert onto plates, and serve immediately with ice cream.',
    ],
    savedAt: Date.now() - 691200000,
  },
];

export const MOCK_GROCERY_ITEMS: GroceryItem[] = [
  { id: 'g1', name: 'Spaghetti', aisle: 'Pasta & Grains', checked: false },
  { id: 'g2', name: 'Pancetta', aisle: 'Deli & Meats', checked: false },
  { id: 'g3', name: 'Pecorino Romano', aisle: 'Dairy & Eggs', checked: true },
  { id: 'g4', name: 'Avocados', aisle: 'Produce', checked: false },
  { id: 'g5', name: 'Sourdough Bread', aisle: 'Bakery', checked: false },
  { id: 'g6', name: 'Chicken Breast', aisle: 'Deli & Meats', checked: false },
  { id: 'g7', name: 'Coconut Cream', aisle: 'Canned Goods', checked: true },
  { id: 'g8', name: 'Feta Cheese', aisle: 'Dairy & Eggs', checked: false },
  { id: 'g9', name: 'Kalamata Olives', aisle: 'Canned Goods', checked: false },
  { id: 'g10', name: 'Dark Chocolate', aisle: 'Baking', checked: false },
];

export const AISLES = [
  'Produce',
  'Dairy & Eggs',
  'Deli & Meats',
  'Pasta & Grains',
  'Canned Goods',
  'Bakery',
  'Baking',
  'Frozen',
  'Beverages',
  'Snacks',
  'Other',
];
